-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kayttaja;
DROP TABLE IF EXISTS Peli;
DROP TABLE IF EXISTS Arvostelu;
DROP TABLE IF EXISTS Statistiikka;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Peli_Genre;


