-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS Statistiikka CASCADE;
DROP TABLE IF EXISTS Arvostelu CASCADE;
DROP TABLE IF EXISTS Peli_Genre CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Peli CASCADE;


